version: '3'

services:
  db:
    image: mysql:5.7.27
    ports:
      - 43306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tests
    # https://github.com/docker-library/docs/issues/613
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
