spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-test-query: SELECT 1
      jdbc-url: jdbc:mysql://localhost:43306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: password

mybatis:
  configuration:
    map-underscore-to-camel-case: true
